name: integration test

on: push 

jobs:
  run:
    name: Integration Test for ShardingSphere Proxy Helm Charts
    runs-on: ubuntu-latest 
    steps:
      - name: "checkout codes" 
        uses: actions/checkout@v3
      - name: "setup kind"
        uses: helm/kind-action@v1.2.0
      - name: "setup helm"
        uses: azure/setup-helm@v2.1
      - name: "setup kubectl" 
        uses: azure/setup-kubectl@v2.0
      - name: "Test Helm Charts for ShardingSphere Proxy"
        run: |
          set -x 
          export TEST_NAMESPACE="shardingsphere-system"
          kubectl create namespace ${TEST_NAMESPACE}
          cd shardingsphere-proxy/charts/governance
          helm dependency build 
          cd ../..
          helm dependency build 
          cd ..
          helm install shardingsphere-proxy shardingsphere-proxy -n ${TEST_NAMESPACE}
          kubectl wait --timeout=60s --for=condition=Ready --all pod -n ${TEST_NAMESPACE}
          kubectl get pod -n ${TEST_NAMESPACE} --show-labels
          sleep 3
